version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:12

orbs:
  node: circleci/node@2.0.2
jobs:
  build-and-test:
    <<: *defaults  
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: 12
      - run: node --version
  deploy:
    <<: *defaults  
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
    build-test-and-deploy:
      jobs:
        - build-and-test:
            filters:
              tags:
                only: /^(\d+\.)*\d+/
        - deploy:
            requires:
              - build-and-test
            filters:
              tags:
                only: /^(\d+\.)*\d+/
              branches:
                only: 
                  - master